# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Tapes"
newsheet "Games"
newsheet "Discounts"
newsheet "Customers"
newsheet "Rentals"
movetosheet "Tapes"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 1
nb_frozen_cols 0
nb_frozen_screenrows 1
nb_frozen_screencols 0
format A 38 2 0
format B 8 0 0
format C 12 2 0
format D 6 2 0
freeze 0
leftstring A0 = "Title"
leftstring B0 = "Runtime"
leftstring C0 = "Genre"
leftstring D0 = "Price"
leftstring A1 = "3 Nights in Rome"
let B1 = 111
leftstring C1 = "Thriller"
let D1 = 9.99
leftstring A2 = "Home for the Family"
let B2 = 103
leftstring C2 = "Holiday"
let D2 = 14.99
leftstring A3 = "Eating Down South - Season 1 (Tape 3)"
let B3 = 120
leftstring C3 = "Cooking"
let D3 = 12.99
leftstring A4 = "First Contact"
let B4 = 97
leftstring C4 = "Sci-Fi"
let D4 = 7.99
leftstring A5 = "Contingency"
let B5 = 146
leftstring C5 = "Action"
let D5 = 18.97
leftstring A6 = "The Last Steam Train"
let B6 = 82
leftstring C6 = "Documentary"
let D6 = 6.99
goto A0
movetosheet "Games"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 1
nb_frozen_cols 0
nb_frozen_screenrows 1
nb_frozen_screencols 0
format A 32 2 0
format B 8 2 0
format C 9 2 0
freeze 0
leftstring A0 = "Title"
leftstring B0 = "Console"
leftstring C0 = "Genre"
leftstring D0 = "Price"
leftstring A1 = "Eyes of the Eagle"
leftstring B1 = "PS2"
leftstring C1 = "Action"
let D1 = 16.99
leftstring A2 = "Knightly Duty"
leftstring B2 = "PSP"
leftstring C2 = "Strategy"
let D2 = 7.99
leftstring A3 = "Street: Crave"
leftstring B3 = "GBA"
leftstring C3 = "Racing"
let D3 = 4.99
leftstring A4 = "First Contact - Close Encounter"
leftstring B4 = "GBA"
leftstring C4 = "Tie-in"
let D4 = 12.95
leftstring A5 = "First Contact - Close Encounter"
leftstring B5 = "PSP"
leftstring C5 = "Tie-in"
let D5 = 13.95
goto A0
movetosheet "Discounts"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 1
nb_frozen_cols 0
nb_frozen_screenrows 1
nb_frozen_screencols 0
format A 11 2 0
format B 11 2 0
format C 5 2 0
format D 32 2 0
format E 6 2 0
freeze 0
leftstring A0 = "Begins"
leftstring B0 = "Ends"
leftstring C0 = "Type"
leftstring D0 = "Title"
leftstring E0 = "% Off"
leftstring F0 = "Notes"
let A1 = @dts(2002,5,1)
fmt A1 "d%m/%d/%Y"
let B1 = @dts(2002,10,1)
fmt B1 "d%m/%d/%Y"
leftstring C1 = "Game"
leftstring D1 = "First Contact - Close Encounter"
let E1 = 15
leftstring F1 = "PSP"
let A2 = @dts(2002,5,1)
fmt A2 "d%m/%d/%Y"
let B2 = @dts(2002,10,1)
fmt B2 "d%m/%d/%Y"
leftstring C2 = "Game"
leftstring D2 = "First Contact - Close Encounter"
let E2 = 14
leftstring F2 = "GBA"
let A3 = @dts(2002,6,30)
fmt A3 "d%m/%d/%Y"
let B3 = @dts(2002,7,22)
fmt B3 "d%m/%d/%Y"
leftstring C3 = "Tape"
leftstring D3 = "Contingency"
let E3 = 30
goto A0
movetosheet "Customers"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 6 2 0
format B 13 2 0
format F 13 2 0
format G 10 0 0
leftstring A0 = "Name"
leftstring B0 = "Phone Number"
leftstring A1 = "Jimbo"
leftstring B1 = "555-####-177"
leftstring A2 = "Ringo"
leftstring B2 = "555-####-420"
leftstring A3 = "Lando"
leftstring B3 = "555-####-112"
leftstring A4 = "Jonno"
leftstring B4 = "555-####-669"
leftstring A5 = "Steve"
leftstring B5 = "555-####-555"
goto A0
movetosheet "Rentals"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 1
nb_frozen_cols 0
nb_frozen_screenrows 1
nb_frozen_screencols 0
format A 11 2 0
format B 9 2 0
format C 5 2 0
format D 38 2 0
format E 11 2 0
format F 11 2 0
format G 5 0 0
format H 6 2 0
format I 20 2 0
freeze 0
leftstring A0 = "Borrowed"
leftstring B0 = "Customer"
leftstring C0 = "Type"
leftstring D0 = "Title"
leftstring E0 = "Due"
leftstring F0 = "Returned"
leftstring G0 = "Late"
leftstring H0 = "Price"
leftstring I0 = "Notes"
let A1 = @dts(2002,3,4)
fmt A1 "d%m/%d/%Y"
leftstring B1 = "Jimbo"
leftstring C1 = "Tape"
leftstring D1 = "3 Nights in Rome"
let E1 = @dts(2002,3,11)
fmt E1 "d%m/%d/%Y"
let F1 = @dts(2002,3,11)
fmt F1 "d%m/%d/%Y"
let G1 = (@avg(E1:F1)-E1)/43200
let H1 = 9.99*((F1-A1)/(86400*7))+1.5*G1
let A2 = @dts(2002,3,6)
fmt A2 "d%m/%d/%Y"
leftstring B2 = "Ringo"
leftstring C2 = "Game"
leftstring D2 = "Street: Crave"
let E2 = @dts(2002,3,13)
fmt E2 "d%m/%d/%Y"
let F2 = @dts(2002,3,15)
fmt F2 "d%m/%d/%Y"
let G2 = (@avg(E2:F2)-E2)/43200
let H2 = 4.99*((F2-A2)/(86400*7))+1.5*G2
let A3 = @dts(2002,4,19)
fmt A3 "d%m/%d/%Y"
leftstring B3 = "Lando"
leftstring C3 = "Tape"
leftstring D3 = "Eating Down South - Season 1 (Tape 3)"
let E3 = @dts(2002,5,10)
fmt E3 "d%m/%d/%Y"
let F3 = @dts(2002,5,10)
fmt F3 "d%m/%d/%Y"
let G3 = (@avg(E3:F3)-E3)/43200
let H3 = 12.99*((F3-A3)/(86400*7))+1.5*G3
let A4 = @dts(2002,5,7)
fmt A4 "d%m/%d/%Y"
leftstring B4 = "Jonno"
leftstring C4 = "Tape"
leftstring D4 = "First Contact"
let E4 = @dts(2002,5,14)
fmt E4 "d%m/%d/%Y"
let F4 = @dts(2002,5,14)
fmt F4 "d%m/%d/%Y"
let G4 = (@avg(E4:F4)-E4)/43200
let H4 = 9.99*((F4-A4)/(86400*7))+1.5*G4
let A5 = @dts(2002,5,15)
fmt A5 "d%m/%d/%Y"
leftstring B5 = "Steve"
leftstring C5 = "Tape"
leftstring D5 = "First Contact"
let E5 = @dts(2002,5,22)
fmt E5 "d%m/%d/%Y"
let F5 = @dts(2002,5,18)
fmt F5 "d%m/%d/%Y"
let G5 = (@avg(E5:F5)-E5)/43200
let H5 = 9.99*((F5-A5)/(86400*7))+1.5*G5
leftstring I5 = "real price is 9.99"
goto A0
